version: '3'
services:
  jalas-back:
    build: ./jalas
    ports:
      - "9092:9092"
    privileged: true

  mysql:
    container_name: mysql
    image: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'jalas'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Abcd12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Abcd12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  jalas-react:
    build: ./jalas-react
    ports:
      - "3000:3000"
    privileged: true

# Names our volume
volumes:
  my-db:

